### ISSUE TITLE
crash: glibc version mismatch

### ISSUE THREAD

**Issue by harryhaaren** [fly-apps/hello-rust#12]
Hi,

The build-docker file has a `rust:latest as build` and uses `debian:bullseye-slim` for runtime image. The glibc version in `rust:latest` is *at this point in time* newer than `debian:bullseye-slim`. The error I see is this:
```
 2023/10/19 20:08:18 listening on [<snip>]:22 (DNS: [fdaa::3]:53)
  ./hello: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./hello)
  ./hello: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./hello)
  ./hello: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./hello)
  Health check on port 8080 is in a 'warning' state. Your app may not be responding properly. Services exposed on ports [80, 443] may have intermittent failures until the health check passes.
```

Best practice is to always "match up" the builder and runtime image, to avoid such glibc-mismatches.
Or go fully static-link, although I don't recommend that for a beginners tutorial ([and other reasons](https://andygrove.io/2020/05/why-musl-extremely-slow/)).

The fix is to use `rust:bullseye` for the builder too... but just changing that didn't actually fix it here.

Regards, -Harry

**Comment by stevenlovegrove** [comment]
Based on the official rust Docker page, I was successful using:
`FROM rust:1.67 as builder`

to match the runner currently listed in the file:
`FROM debian:bullseye-slim`

To deploy successfully, I additionally had to change the app name to something unique in fly.toml.

**Comment by kzsh** [comment]
I _think_ my PR will address this for our-of-the-box runs 
https://github.com/fly-apps/hello-rust/pull/13

**Comment by harryhaaren** [comment]
Untested, but this should be fixed by https://github.com/fly-apps/hello-rust/pull/13, thanks @kzsh for the PR!
