### ISSUE TITLE
Not using the official docker image

### ISSUE THREAD

**Issue by brleinad** [fly-apps/hello-rust#2]
Is there a reason why this example doesn't use the [official rust docker image](https://hub.docker.com/_/rust/)?
I ran into issues with the `Dockerfile` in this example because `liuchong/rustup:stable` is not up to date and was getting a

```
error: failed to parse manifest at `Cargo.toml`

Caused by:
  feature `edition2021` is required
```

My cargo file had something like 
```
[package]
edition = "2021"

```
And I had to change it to `edition = "2018"`, to work with the `Dockerfile` in this example, even though the latest stable rust release supports [edition 2021](https://github.com/rust-lang/rust/blob/master/RELEASES.md#language-4).

I can look into opening a PR for this if this is something that could be helpful for others.

**Comment by jeromegn** [comment]
A PR would be appreciated.

This is meant as an example app and was built a while ago! IIRC, I didn't love how the official image worked. It's probably a safer bet to use it though.

**Comment by brleinad** [comment]
Cool good to know, I'll work on the PR in the next few days. 
I understand it's just an example but it's the only one I could find of deploying a Rust to fly.io so thanks a lot for this example!
